add check for semver and build date in replace_binary()
k3s-io/k3s-upgrade pull request #66
Opened 2023-06-19 15:42 UTC by osodracnai

adding bail out for some incorrect upgrades https://github.com/k3s-io/k3s/issues/7537

2023-06-21 18:42 UTC, dereknola approved these changes

2023-06-27 18:12 UTC, brandond requested changes
Nit on the error text, but looks good otherwise!

2023-06-27 18:12 UTC, brandond commented on scripts/upgrade.sh
> +    echo "Error: Version ${FULL_BIN_SEMVER} is more recent than ${NEW_BIN_SEMVER}"
```suggestion
    echo "Error: Current version ${FULL_BIN_SEMVER} is higher than ${NEW_BIN_SEMVER}"
```

2023-06-27 18:12 UTC, brandond commented on scripts/upgrade.sh
> +    echo "Error: Version ${FULL_BIN_SEMVER} is more recent than ${NEW_BIN_SEMVER}"
```suggestion
    echo "Error: Current build date ${FULL_BIN_RELEASE_DATE} is more recent than ${NEW_BIN_RELEASE_DATE}"
```

2023-06-28 16:46 UTC, brandond approved these changes

2023-07-11 16:40 UTC, merged